from __future__ import annotations

import argparse
import base64
import json
from dataclasses import dataclass
from pathlib import Path

import cv2
import render_common as rc
import yaml
from openai import OpenAI

try:
    from tqdm import tqdm
except ImportError:
    tqdm = None


@dataclass(frozen=True)
class Segment:
    index: int
    start_sec: float
    end_sec: float

    @property
    def center_sec(self) -> float:
        return 0.5 * (self.start_sec + self.end_sec)


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Annotate per-segment compliance values by asking GPT whether the "
            "robot may yield in xy, z, rpy, and posture during each segment."
        )
    )
    parser.add_argument(
        "segment_yaml",
        help="Input YAML with video_path and boundaries_sec generated by segment_video.py.",
    )
    parser.add_argument(
        "--task_description",
        default="",
        help="Short text describing the task shown in the video.",
    )
    parser.add_argument(
        "--model",
        default="gpt-5.4",
        help="OpenAI model name. Default: gpt-5.4",
    )
    parser.add_argument(
        "--frame_jpeg_quality",
        type=int,
        default=90,
        help="JPEG quality for uploaded frames.",
    )
    parser.add_argument(
        "--save_prompt_images",
        action="store_true",
        help="Save the center-frame images sent to the model for debugging.",
    )
    parser.add_argument(
        "--render_suffix",
        default=".annotated_compliance",
        help="Suffix added before the rendered video extension.",
    )
    parser.add_argument(
        "--render_fps",
        type=float,
        default=None,
        help="Override output fps. Defaults to the source video fps.",
    )
    return parser.parse_args()


def resolve_output_paths(segment_yaml_path: Path, video_path: Path, render_suffix: str):
    output_yaml_path = segment_yaml_path.with_name(f"{segment_yaml_path.stem}_compliance.yaml")
    decision_json_path = output_yaml_path.with_suffix(f"{output_yaml_path.suffix}.json")
    rendered_video_path = Path(rc.build_output_path(str(video_path), render_suffix))
    prompt_image_dir = output_yaml_path.with_name(f"{output_yaml_path.stem}_prompt_images")
    return output_yaml_path, decision_json_path, rendered_video_path, prompt_image_dir


def load_segment_yaml(segment_yaml_path: Path):
    with open(segment_yaml_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    if not isinstance(config, dict):
        raise ValueError("Top-level YAML object must be a mapping.")
    if "video_path" not in config:
        raise KeyError("segment YAML must contain video_path.")
    if "boundaries_sec" not in config:
        raise KeyError("segment YAML must contain boundaries_sec.")

    video_path = Path(config["video_path"]).expanduser().resolve()
    boundaries_sec = [float(v) for v in config["boundaries_sec"]]
    if len(boundaries_sec) < 2:
        raise ValueError("boundaries_sec must contain at least two values.")
    if sorted(boundaries_sec) != boundaries_sec:
        raise ValueError("boundaries_sec must be sorted in ascending order.")
    if boundaries_sec[0] != 0.0:
        raise ValueError("boundaries_sec must start at 0.0.")
    return video_path, boundaries_sec, config


def build_segments(boundaries_sec: list[float]) -> list[Segment]:
    return [
        Segment(index=i, start_sec=start_sec, end_sec=end_sec)
        for i, (start_sec, end_sec) in enumerate(zip(boundaries_sec[:-1], boundaries_sec[1:]))
    ]


def open_video_capture(video_path: Path):
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise RuntimeError(f"Failed to open video: {video_path}")
    return cap


def get_video_info(cap):
    fps = float(cap.get(cv2.CAP_PROP_FPS))
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if fps <= 0 or frame_count <= 0:
        raise RuntimeError("Failed to read video fps or frame count.")
    return fps, frame_count


def sec_to_frame_index(cap, sec: float) -> int:
    fps, frame_count = get_video_info(cap)
    frame_idx = int(round(sec * fps))
    return max(0, min(frame_idx, frame_count - 1))


def read_frame_at_sec(cap, sec: float):
    frame_idx = sec_to_frame_index(cap, sec)
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
    ok, frame_bgr = cap.read()
    if not ok or frame_bgr is None:
        raise RuntimeError(f"Failed to read frame at {sec:.3f} sec.")
    frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
    return frame_rgb, frame_idx


def encode_frame_as_data_url(frame_rgb, jpeg_quality: int) -> str:
    ok, encoded = cv2.imencode(
        ".jpg",
        cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2BGR),
        [cv2.IMWRITE_JPEG_QUALITY, jpeg_quality],
    )
    if not ok:
        raise RuntimeError("Failed to encode frame as JPEG.")
    encoded_b64 = base64.b64encode(encoded.tobytes()).decode("utf-8")
    return f"data:image/jpeg;base64,{encoded_b64}"


def save_prompt_image(frame_rgb, output_path: Path, jpeg_quality: int) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    ok = cv2.imwrite(
        str(output_path),
        cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2BGR),
        [cv2.IMWRITE_JPEG_QUALITY, jpeg_quality],
    )
    if not ok:
        raise RuntimeError(f"Failed to save prompt image: {output_path}")


def extract_json_dict(text: str) -> dict:
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        start = text.find("{")
        end = text.rfind("}")
        if start == -1 or end == -1 or end <= start:
            raise
        return json.loads(text[start : end + 1])


def ask_gpt_for_segment_annotation(
    client: OpenAI,
    model: str,
    task_description: str,
    segment: Segment,
    center_image_url: str,
) -> dict:
    task_text = task_description.strip() or "No extra task description is provided."
    prompt = (
        "Judge compliance for a robot manipulator video segment.\n"
        "\n"
        "Compliance means whether motion caused by external force is acceptable.\n"
        "For xy, z, and rpy, judge whether small motion is acceptable.\n"
        "For posture, judge whether elbow or redundant arm motion is acceptable.\n"
        "\n"
        "Use the image as the primary evidence.\n"
        "Use the task description together with the image to understand the task and judge appropriate compliance.\n"
        "Do not assume hidden objects, future events, invisible contacts, or supported payloads unless they are clearly visible or explicitly described.\n"
        "\n"
        "Return JSON only with these keys:\n"
        "xy_compliance, z_compliance, rpy_compliance, posture_compliance, reasons\n"
        "\n"
        "The compliance values must be consistent with the reasons.\n"
        "If the reasons say compliance is acceptable, the value must be 1.\n"
        "If the reasons say compliance is not desirable, the value must be 0.\n"
        "\n"
        "Definitions:\n"
        "xy: small horizontal end-effector motion\n"
        "z: small vertical end-effector motion\n"
        "rpy: small orientation change of the end-effector\n"
        "posture: elbow or redundant arm motion\n"
        "\n"
        f"Task description: {task_text}\n"
        f"Segment time range: {segment.start_sec:.3f} - {segment.end_sec:.3f} sec."
    )
    response = client.responses.create(
        model=model,
        input=[
            {
                "role": "user",
                "content": [
                    {"type": "input_text", "text": prompt},
                    {
                        "type": "input_text",
                        "text": "This image is at the center time of the segment.",
                    },
                    {"type": "input_image", "image_url": center_image_url, "detail": "high"},
                ],
            }
        ],
    )
    result = extract_json_dict(response.output_text)
    annotation = {
        "xy_compliance": int(result["xy_compliance"]),
        "z_compliance": int(result["z_compliance"]),
        "rpy_compliance": int(result["rpy_compliance"]),
        "posture_compliance": int(result["posture_compliance"]),
        "reasons": result.get("reasons", {}),
        "raw_text": response.output_text,
        "response_id": response.id,
    }
    for key in ("xy_compliance", "z_compliance", "rpy_compliance", "posture_compliance"):
        if annotation[key] not in (0, 1):
            raise ValueError(f"{key} must be 0 or 1, got {annotation[key]}")
    return annotation


def annotate_segments(
    cap,
    client: OpenAI,
    model: str,
    task_description: str,
    segments: list[Segment],
    jpeg_quality: int,
    prompt_image_dir: Path | None,
) -> list[dict]:
    annotations = []
    iterator = segments
    if tqdm is not None:
        iterator = tqdm(iterator, desc="Annotating segments", total=len(segments))
    for segment in iterator:
        center_rgb, center_idx = read_frame_at_sec(cap, segment.center_sec)
        prompt_image_path = None
        if prompt_image_dir is not None:
            prompt_image_path = prompt_image_dir / f"segment_{segment.index:04d}_center.jpg"
            save_prompt_image(center_rgb, prompt_image_path, jpeg_quality)
        decision = ask_gpt_for_segment_annotation(
            client=client,
            model=model,
            task_description=task_description,
            segment=segment,
            center_image_url=encode_frame_as_data_url(center_rgb, jpeg_quality),
        )
        annotations.append(
            {
                "segment_index": segment.index,
                "start_sec": segment.start_sec,
                "end_sec": segment.end_sec,
                "center_frame_idx": center_idx,
                "prompt_image_path": str(prompt_image_path) if prompt_image_path is not None else None,
                **decision,
            }
        )
    return annotations


def save_outputs(
    output_yaml_path: Path,
    decision_json_path: Path,
    original_config: dict,
    video_path: Path,
    annotations: list[dict],
) -> None:
    output_yaml_path.parent.mkdir(parents=True, exist_ok=True)
    decision_json_path.parent.mkdir(parents=True, exist_ok=True)

    output_config = dict(original_config)
    output_config["video_path"] = str(video_path)
    output_config["segment_annotations"] = [
        {
            "segment_index": item["segment_index"],
            "start_sec": item["start_sec"],
            "end_sec": item["end_sec"],
            "xy_compliance": item["xy_compliance"],
            "z_compliance": item["z_compliance"],
            "rpy_compliance": item["rpy_compliance"],
            "posture_compliance": item["posture_compliance"],
        }
        for item in annotations
    ]
    with open(output_yaml_path, "w", encoding="utf-8") as f:
        yaml.safe_dump(output_config, f, sort_keys=False, allow_unicode=True)

    with open(decision_json_path, "w", encoding="utf-8") as f:
        json.dump(annotations, f, indent=2, ensure_ascii=False)


def load_video_frames_rgb(video_path: Path):
    cap = open_video_capture(video_path)
    fps, _ = get_video_info(cap)
    frames = []
    try:
        while True:
            ok, frame_bgr = cap.read()
            if not ok or frame_bgr is None:
                break
            frames.append(cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB))
    finally:
        cap.release()
    if not frames:
        raise RuntimeError(f"Failed to load frames from video: {video_path}")
    return rc.np.stack(frames, axis=0), fps


def build_compliance_series(
    annotations: list[dict],
    num_frames: int,
    fps: float,
) -> dict[str, rc.np.ndarray]:
    names = ["xy_compliance", "z_compliance", "rpy_compliance", "posture_compliance"]
    series = {name: rc.np.zeros(num_frames, dtype=rc.np.float32) for name in names}
    for item in annotations:
        start = max(0, min(num_frames - 1, int(round(item["start_sec"] * fps))))
        end = max(start, min(num_frames, int(round(item["end_sec"] * fps))))
        for name in names:
            series[name][start:end] = float(item[name])
    return series


def draw_step_series(draw, xs, ys, color, width):
    points = []
    for idx in range(len(xs)):
        if idx == 0:
            points.append((xs[idx], ys[idx]))
        else:
            points.append((xs[idx], ys[idx - 1]))
            points.append((xs[idx], ys[idx]))
    if len(points) >= 2:
        draw.line(points, fill=color, width=width)


def build_compliance_panel_background(series: dict[str, rc.np.ndarray], width: int, row_height: int = 70):
    labels = [
        ("xy", "xy_compliance", (53, 164, 245)),
        ("z", "z_compliance", (52, 199, 89)),
        ("rpy", "rpy_compliance", (243, 156, 18)),
        ("posture", "posture_compliance", (231, 76, 60)),
    ]
    left_pad = 110
    right_pad = 18
    top_pad = 16
    bottom_pad = 16
    total_height = top_pad + bottom_pad + row_height * len(labels)
    panel = rc.Image.new("RGB", (width, total_height), (248, 248, 248))
    draw = rc.ImageDraw.Draw(panel)
    label_font = rc.load_font(22)
    axis_font = rc.load_font(18)
    plot_x0 = left_pad
    plot_x1 = max(plot_x0 + 10, width - right_pad)
    plot_width = max(1, plot_x1 - plot_x0)
    num_frames = len(next(iter(series.values())))
    x_values = rc.np.linspace(plot_x0, plot_x1, num_frames, dtype=rc.np.int64)

    for row_idx, (label, key, color) in enumerate(labels):
        row_top = top_pad + row_idx * row_height
        row_bottom = row_top + row_height
        y_high = row_top + 14
        y_low = row_bottom - 14
        draw.text((16, row_top + 18), label, fill=(0, 0, 0), font=label_font)
        draw.line((plot_x0, y_high, plot_x1, y_high), fill=(210, 210, 210), width=1)
        draw.line((plot_x0, y_low, plot_x1, y_low), fill=(210, 210, 210), width=1)
        draw.text((plot_x0 - 28, y_high - 10), "1", fill=(100, 100, 100), font=axis_font)
        draw.text((plot_x0 - 28, y_low - 10), "0", fill=(100, 100, 100), font=axis_font)
        values = rc.np.clip(series[key], 0.0, 1.0)
        y_values = y_low - values * (y_low - y_high)
        draw_step_series(draw, x_values, y_values, color=color, width=3)

    return panel


def render_annotated_compliance_video(
    video_path: Path,
    annotations: list[dict],
    render_suffix: str,
    render_fps: float | None,
):
    rc.import_rendering_dependencies()
    frames, source_fps = load_video_frames_rgb(video_path)
    fps = render_fps or source_fps or 30.0
    series = build_compliance_series(annotations, num_frames=len(frames), fps=source_fps)
    panel_background = build_compliance_panel_background(series, width=frames.shape[2])
    panel_background_np = rc.np.array(panel_background, dtype=rc.np.uint8)
    panel_height = panel_background_np.shape[0]
    x_positions = rc.np.linspace(110, frames.shape[2] - 18, len(frames), dtype=rc.np.int64)

    iterator = range(len(frames))
    if tqdm is not None:
        iterator = tqdm(iterator, desc="Rendering compliance video", total=len(frames))
    rendered_frames = []
    for frame_idx in iterator:
        panel = panel_background_np.copy()
        current_x = int(x_positions[frame_idx])
        panel[:, max(0, current_x - 1) : min(panel.shape[1], current_x + 2)] = (0, 0, 0)
        rendered_frames.append(rc.np.concatenate([frames[frame_idx], panel], axis=0))

    rendered = rc.np.stack(rendered_frames, axis=0)
    output_path = Path(rc.build_output_path(str(video_path), render_suffix))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    rc.save_video_ffmpeg(rendered, str(output_path), fps=fps)
    return output_path


def main():
    args = parse_args()
    segment_yaml_path = Path(args.segment_yaml).expanduser().resolve()
    video_path, boundaries_sec, original_config = load_segment_yaml(segment_yaml_path)
    output_yaml_path, decision_json_path, rendered_video_path, prompt_image_dir = resolve_output_paths(
        segment_yaml_path=segment_yaml_path,
        video_path=video_path,
        render_suffix=args.render_suffix,
    )
    segments = build_segments(boundaries_sec)
    client = OpenAI()

    print(f"[1/4] Loading segment YAML: {segment_yaml_path}", flush=True)
    cap = open_video_capture(video_path)
    try:
        print(f"[2/4] Annotating {len(segments)} segments with {args.model}", flush=True)
        annotations = annotate_segments(
            cap=cap,
            client=client,
            model=args.model,
            task_description=args.task_description,
            segments=segments,
            jpeg_quality=args.frame_jpeg_quality,
            prompt_image_dir=prompt_image_dir if args.save_prompt_images else None,
        )
    finally:
        cap.release()

    print(f"[3/4] Saving YAML and JSON outputs", flush=True)
    save_outputs(
        output_yaml_path=output_yaml_path,
        decision_json_path=decision_json_path,
        original_config=original_config,
        video_path=video_path,
        annotations=annotations,
    )

    print(f"[4/4] Rendering annotated compliance video", flush=True)
    rendered_video_path = render_annotated_compliance_video(
        video_path=video_path,
        annotations=annotations,
        render_suffix=args.render_suffix,
        render_fps=args.render_fps,
    )

    print(f"Saved compliance YAML to: {output_yaml_path}")
    print(f"Saved decision JSON to: {decision_json_path}")
    print(f"Saved compliance video to: {rendered_video_path}")


if __name__ == "__main__":
    main()
